name = "gssFortran"
version = "0.1.0"
license = "license"
author = "huijunchen9260"
maintainer = "chen.9260@osu.edu"
copyright = "Copyright 2022, huijunchen9260"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
